disabled_rules: # rule identifiers to exclude from running
- force_cast
- force_try
- nesting
- trailing_whitespace
- type_name
- identifier_name
# - shorthand_operator
# - comma
# - control_statement
# - file_length
# - function_body_length
# - leading_whitespace
# - line_length
# - operator_whitespace
- redundant_void_return
- colon
- opening_brace
- return_arrow_whitespace
# - statement_position
# - todo
# - trailing_newline
# - trailing_semicolon
# - type_body_length
# - valid_docs
# - variable_name
# - variable_name_min_length
# - variable_name_max_length
excluded: # paths to ignore during linting. overridden by `included`.
- Carthage
- Pods
- fastlane
- PublicCode
# parameterized rules can be customized from this configuration file
file_length:
- 700
- 1000
line_length:
- 230
- 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
- 150 # warning
- 200 # error
type_body_length:
- 300 # warning
- 400 # error
variable_name_max_length:
- 30 # warning
- 40 # error
variable_name_min_length:
- 2 # warning
- 1 # error

