//
//  SampleVIP_Models.swift
//  GoodToGo
//
//  Created by Ricardo Santos on 10/10/2019.
//  Copyright (c) 2019 Ricardo P Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK:- Interactor

protocol SampleVIP_BusinessLogic {
  func doSomething(request: SampleVIP.SearchView.Request)
}

protocol SampleVIP_DataStore {
  //var name: String { get set }
}

enum SampleVIP {
  // MARK: Use cases
  
  enum SearchView {
    struct Request { }
    struct Response { }
    struct ViewModel {
        let name: String
    }
  }
}
