//
//  SampleVIP_Presenter.swift
//  GoodToGo
//
//  Created by Ricardo Santos on 10/10/2019.
//  Copyright (c) 2019 Ricardo P Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SampleVIP_PresentationLogic {
  func presentSomething(response: SampleVIP.SearchView.Response)
}

class SampleVIP_Presenter: SampleVIP_PresentationLogic {
  weak var viewController: SampleVIP_DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SampleVIP.SearchView.Response) {
    let viewModel = SampleVIP.SearchView.ViewModel(name: "name")
    viewController?.displaySomething(viewModel: viewModel)
  }
}
