//
//  StatsDetailModels.swift
//  i9
//
//  Created by Marcelo Antunes on 12/26/18.
//  Copyright (c) 2018 Crédito Agrícola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Domain
import Differentiator
import Designables

enum StatsDetail {
    // MARK: Use cases

    enum DisplayScreen {
        struct Request {
        }

        struct Response {
        }

        struct ViewModel {
            let lottieAnimation: String
            let cloudTitle: String
            let seeAllButtonTitle: String
        }
    }

    enum SeeAll {
        struct Request {
        }

        struct Response {
        }

        struct ViewModel {
            let tableItems: [Stats.TableItem]
        }
    }

    enum Info {
        struct Request {
        }

        struct Response {
            let showCategoryInTitle: Bool
            let showCurrentTimeInTransactionGroup: Bool
            let period: StatsPeriod
            let info: StatsDetail.WorkerModel
        }

        struct ViewModel {
            let showCurrentTimeInTransactionGroup: Bool
            let headerInfo: StatsDetail.HeaderInfo
            let tableItems: [Stats.TableItem]
        }
    }
}

extension StatsDetail {

    struct HeaderInfo {
        let categoryGroupColor: UIColor
        let category: Domain.TransactionCategory?
        let images: [AvatarImage]
        let title: String
        let subtitle: String

        let fakeCellTitle: String
        let fakeCellMonth: String
        let fakeCellAmount: String
        let fakeCellTransactionsCount: String
        let fakeCellPercentageString: String
        let fakeCellPercentageValue: Float
    }

    struct WorkerModel {
        let categoryGroupColor: UIColor
        let headerImages: [AvatarImage]
        let headerTitle: String
        let headerTotalAmount: Amount
        let headerMaxAmount: Amount
        let headerTransactionsCount: Int
        let headerPercentageValue: Float
        let category: Domain.TransactionCategory?
        let workerListModel: [WorkerItem]

        struct WorkerItem {
            let id: String
            let categoryGroupColor: UIColor
            let images: [AvatarImage]
            let title: String
            let date: Date?
            let transactionsCount: Int
            let amount: Amount
            let percentageValue: Float?

            init(
                id: String,
                categoryGroupColor: UIColor,
                images: [AvatarImage],
                title: String,
                date: Date?,
                transactionsCount: Int,
                amount: Amount,
                percentageValue: Float?) {
                self.id = String(describing: id)
                self.categoryGroupColor = categoryGroupColor
                self.images = images
                self.title = title
                self.date = date
                self.transactionsCount = transactionsCount
                self.amount = amount
                self.percentageValue = percentageValue
            }
        }
    }

}
