//
//  StatsDetailRoutingLogic.swift
//  i9
//
//  Created by Marcelo Antunes on 12/26/18.
//  Copyright (c) 2018 Crédito Agrícola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Domain

protocol StatsDetailRoutingLogic {
    func routeToStatsDetail(id: String)
}

protocol StatsDetailDataPassing {
    var dataStore: StatsDetailDataStore? { get }
}
