

#
# DOCS
#
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

#
# SAMPLES
#
# https://gist.github.com/d-date/44510c5b4b3baf820033453bfeb235c3
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Examples.md
#

####################### PROJECT #######################
####################### PROJECT #######################  
####################### PROJECT #######################

name: RJSLibUF

options:
  bundleIdPrefix: com.rjps.libuf
  xcodeVersion: '12.0.1'
  deploymentTarget: '10.0'
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: false
  minimumXcodeGenVersion: '2.18.0'

####################### AUXILIAR FOLDERS #######################
####################### AUXILIAR FOLDERS #######################  
####################### AUXILIAR FOLDERS #######################

#fileGroups:
#  - ./_Documentation_

####################### CONFIGS #######################
####################### CONFIGS #######################  
####################### CONFIGS #######################

configs:
  Debug: debug
  Release: release
  
####################### SETTINGS #######################
####################### SETTINGS #######################  
####################### SETTINGS #######################

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 10.0
    ENABLE_BITCODE: NO
    SWIFT_VERSION: 5.2
  configs:
    Release: 
      ENABLE_BITCODE: YES
     
targetTemplates:
  Framework:
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    settings:
      base:
        MARKETING_VERSION: 1.0
    
####################### TARGETS #######################
####################### TARGETS #######################  
####################### TARGETS #######################
       
targets:
        
## Base App

  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    settings:
      base:
        MARKETING_VERSION: 1.0
    sources:
       - path: ../SampleApp
    dependencies:
      - target: RJSLibUFBase
        link: true
      - target: RJSLibUFAppThemes
        link: true
      - target: RJSLibUFNetworking
        link: true
      - target: RJSLibUFALayouts
        link: true
      - target: RJSLibUFStorage
        link: true
    postCompileScripts:
      - script: |
                if which swiftlint >/dev/null; then
                   swiftlint
                else
                   echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        name: Run SwiftLint
   
       
## RJSLib
     
  RJSLibUFBase:
    templates: 
      - Framework
    sources: 
      - path: ../Base
        
  RJSLibUFAppThemes:
    templates: 
      - Framework
    sources: 
      - path: ../AppThemes
    dependencies:
      - target: RJSLibUFBase
        link: false
        
  RJSLibUFNetworking:
    templates: 
      - Framework
    sources: 
      - path: ../Networking  
    dependencies:
      - target: RJSLibUFBase
        link: false

  RJSLibUFALayouts:
    templates: 
      - Framework
    sources: 
      - path: ../ALayouts  
    dependencies:
      - target: RJSLibUFBase
        link: false

  RJSLibUFStorage:
    templates: 
      - Framework
    sources: 
      - path: ../Storage  
    dependencies:
      - target: RJSLibUFBase
        link: false

####################### TARGETS #######################
####################### TARGETS #######################
####################### TARGETS #######################

  SampleAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
       - path: ../SampleAppTests
    scheme: {}
    dependencies:
      - target: SampleApp
        link: false
      - target: RJSLibUFBase
        link: false
      - target: RJSLibUFNetworking
        link: false
      - target: RJSLibUFALayouts
        link: false
      - target: RJSLibUFStorage
        link: false

