

#
# DOCS
#
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

#
# SAMPLES
#
# https://gist.github.com/d-date/44510c5b4b3baf820033453bfeb235c3
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Examples.md
#

####################### PROJECT #######################
####################### PROJECT #######################  
####################### PROJECT #######################

name: GoodToGo

options:

  bundleIdPrefix: com.GoodToGo
  xcodeVersion: '12.0.1'
  deploymentTarget: '12.0'
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: false
  minimumXcodeGenVersion: '2.18.0'

####################### AUXILIAR FOLDERS #######################
####################### AUXILIAR FOLDERS #######################  
####################### AUXILIAR FOLDERS #######################

fileGroups:

  - ../Documents

####################### CONFIGS #######################
####################### CONFIGS #######################  
####################### CONFIGS #######################

configs:

  Debug.Mock: debug
  Debug.Dev: debug
  Debug.QA: debug
  Debug.Prod: debug
  Release: release

####################### SPM #######################
####################### SPM #######################  
####################### SPM #######################

## MORE LIBRARIES HERE :
##  https://github.com/Wolg/awesome-swift
##  https://github.com/vsouza/awesome-ios
##  https://github.com/duemunk/awesome-swiftui

packages:

  RJSLibUF:
    url: https://github.com/ricardopsantos/RJSLibUF
    branch: master
    #minVersion: 1.0.0, maxVersion: 2.0.0

# Pulse animation for iOS
  Pulsator:
    url: https://github.com/shu223/Pulsator
    branch: master
    
# A beautiful and flexible text field control implementation of "Float Label Pattern". Written in Swift.
  SkyFloatingLabelTextField:
    url: https://github.com/Skyscanner/SkyFloatingLabelTextField
    branch: master
    
# A Swift extension that adds toast notifications to the UIView object class.
  Toast:
    url: https://github.com/scalessec/Toast-Swift
    branch: master

# Alamofire is an HTTP networking library written in Swift.
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    branch: master

# Swinject is a lightweight dependency injection framework for Swift.
  Swinject:
    url: https://github.com/Swinject/Swinject
    branch: master
  SwinjectAutoregistration:
    url: https://github.com/Swinject/SwinjectAutoregistration
    branch: master

# UI/UX framework for creating beautiful applications
  Material:
    url: https://github.com/CosmicMind/Material
    branch: master
  Motion:
    url: https://github.com/CosmicMind/Motion
    branch: master
   
# Hero is a library for building iOS view controller transitions   
  Hero:
    url: https://github.com/HeroTransitions/Hero
    branch: master
   
# Nothing but sugar.
  TinyConstraints:
    url: https://github.com/roberthein/TinyConstraints
    branch: master
    
# An iOS library to natively render After Effects vector animations http://airbnb.io/lottie/
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    branch: master

####################### SETTINGS #######################
####################### SETTINGS #######################  
####################### SETTINGS #######################

settings:

  base:
    IPHONEOS_DEPLOYMENT_TARGET: 12.0
    ENABLE_BITCODE: NO
    SWIFT_VERSION: 5.2
    
  configs:
    Release: 
      ENABLE_BITCODE: YES
   
   
####################### TEMPLATES #######################
####################### TEMPLATES #######################  
####################### TEMPLATES #######################
  
targetTemplates:

  Framework:
    type: framework
    platform: iOS
    deploymentTarget: 11.0
    settings:
      base:
        MARKETING_VERSION: 1.0

  UIFramework:
    type: framework
    platform: iOS
    deploymentTarget: 11.0
    settings:
      base:
        MARKETING_VERSION: 1.0
            
####################### TARGETS #######################
####################### TARGETS #######################  
####################### TARGETS #######################
       
targets:
  
## Main Target ## Main Target ## Main Target ## Main Target ## Main Target ## Main Target 
## Main Target ## Main Target ## Main Target ## Main Target ## Main Target ## Main Target 
## Main Target ## Main Target ## Main Target ## Main Target ## Main Target ## Main Target 

  GoodToGo:
    type: application
    platform: iOS
    deploymentTarget: 12.0
    settings:
      base:
        MARKETING_VERSION: 1.0
      configs:
        Debug.Dev: 
          CUSTOM_BUILD_SETTING: my_value_1
        Debug.QA:
          CUSTOM_BUILD_SETTING: my_value_2
        Debug.Prod:
          CUSTOM_BUILD_SETTING: my_value_3
        Debug.Mock:
          CUSTOM_BUILD_SETTING: my_value_5
        debug:
          CUSTOM_BUILD_SETTING: my_value_6
        release:
          CUSTOM_BUILD_SETTING: my_value_7
    sources:
       - path: ../GoodToGo
    dependencies:
      - carthage: RxRelay
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: Differentiator
      - carthage: RxDataSources
      - carthage: RxGesture
      - package: Material
        product: Material
        link: true
      - package: Motion
        product: Motion
        link: true
      - package: TinyConstraints
        product: TinyConstraints
        link: true  
      - package: Hero
        product: Hero
        link: true            
      - package: Swinject
        product: Swinject
        link: true 
      - package: SwinjectAutoregistration
        product: SwinjectAutoregistration
        link: true 
      - package: Alamofire
        product: Alamofire
        link: true 
      - package: Toast
        product: Toast
        link: true 
      - package: SkyFloatingLabelTextField
        product: SkyFloatingLabelTextField
        link: true 
      - package: Pulsator
        product: Pulsator
        link: true 
      - package: RJSLibUF
        product: RJSLibUFBase
        product: RJSLibUFStorage
        product: RJSLibUFNetworking
    
      - target: UICarTrack
        link: true
      - target: UIGalleryApp
        link: true
        
    postCompileScripts:
      - script: |
                if which swiftlint >/dev/null; then
                   swiftlint
                else
                   echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        name: Run SwiftLint
   
## Specific App Related ## Specific App Related ## Specific App Related ## Specific App Related
## Specific App Related ## Specific App Related ## Specific App Related ## Specific App Related
## Specific App Related ## Specific App Related ## Specific App Related ## Specific App Related

  UICarTrack:
    templates: 
      - UIFramework
    sources: 
      - path: ../UICarTrack
    dependencies:
      - carthage: RxRelay
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: Differentiator
      - carthage: RxDataSources
      - package: Material
        product: Material
        link: false
      - package: Motion
        product: Motion
        link: false
      - package: TinyConstraints
        product: TinyConstraints
        link: false
      - package: Swinject
        product: Swinject
        link: false
      - package: SwinjectAutoregistration
        product: SwinjectAutoregistration
        link: false
        
      - target: DomainCarTrack
        link: false
      - target: CoreCarTrack
        link: false
      - target: RepositoryWebAPICartrack
        link: false
      - target: Designables
        link: false   
       
       
              
  DomainCarTrack:
    templates: 
      - Framework
    sources: 
      - path: ../DomainCarTrack
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFNetworking  
        link: false
      - target: BaseDomain
        link: false
      
      
      
  CoreCarTrack:
    templates: 
      - Framework
    sources: 
      - path: ../CoreCarTrack
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - target: BaseCore
        link: false  



  RepositoryWebAPICartrack:
    templates: 
      - Framework
    sources: 
      - path: ../RepositoryWebAPICartrack  
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFNetworking 
        link: true 
      - target: BaseRepositoryWebAPI
        link: false  
      - target: BaseConstants
        link: false  
      - target: DevTools
        link: false
      - target: DomainCarTrack
        link: false



## Specific App Related ## Specific App Related ## Specific App Related ## Specific App Related
## Specific App Related ## Specific App Related ## Specific App Related ## Specific App Related
## Specific App Related ## Specific App Related ## Specific App Related ## Specific App Related



  UIGalleryApp:
    templates:
      - UIFramework
    sources:
      - path: ../UIGalleryApp
    dependencies:
      - carthage: RxRelay
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: Differentiator
      - carthage: RxDataSources
        
      - package: RJSLibUF
        product: RJSLibUFNetworking  
        link: false
      - target: DomainGalleryApp
        link: false
      - target: CoreGalleryApp
        link: false
      - target: RepositoryWebAPIGalleryApp
        link: false
      - target: DevTools
        link: false
      - target: BaseCore
        link: false  
      - target: Designables
        link: false
 
 
        
  RepositoryWebAPIGalleryApp:
    templates: 
      - Framework
    sources: 
      - path: ../RepositoryWebAPIGalleryApp  
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFNetworking  
        link: true
      - target: BaseRepositoryWebAPI
        link: false  
      - target: BaseConstants
        link: false  
      - target: DevTools
        link: false   
      - target: DomainGalleryApp
        link: false   
               
               
               
  DomainGalleryApp:
    templates: 
      - Framework
    sources: 
      - path: ../DomainGalleryApp   
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFNetworking
        link: false  
      - target: BaseDomain
        link: false  
       
       
       
  CoreGalleryApp:
    templates: 
      - Framework
    sources: 
      - path: ../CoreGalleryApp  
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - target: BaseCore
        link: false 
      - target: DomainGalleryApp
        link: false    
      
      
      
## Generic App Related ## Generic App Related ## Generic App Related ## Generic App Related
## Generic App Related ## Generic App Related ## Generic App Related ## Generic App Related
## Generic App Related ## Generic App Related ## Generic App Related ## Generic App Related



  BaseRepositoryWebAPI:
    templates: 
      - Framework
    sources: 
      - path: ../BaseRepositoryWebAPI
    dependencies: 
      - package: Alamofire 
        product: Alamofire
        link: true
      - target: DevTools
        link: false  
         
         
         
  Designables:
    templates: 
      - Framework
    sources: 
      - path: ../Designables
    dependencies:
      - package: TinyConstraints
        product: TinyConstraints
        link: true
      - package: Material
        product: Material
        link: true
      - package: Motion
        product: Motion
        link: true
      - package: Lottie
        product: Lottie
        link: true
      - package: SkyFloatingLabelTextField
        product: SkyFloatingLabelTextField
        link: true
      - package: RJSLibUF
        product: RJSLibUFBase
        product: RJSLibUFALayouts 
        link: true
      - target: BaseUI
        link: false
         
         
                  
  BaseUI:
    templates: 
      - Framework
    sources: 
      - path: ../BaseUI
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        product: RJSLibUFAppThemes
        link: true
      - target: AppResources
        link: false
      - target: AppTheme
        link: false
      - target: BaseCore
        link: false
 
 
 
  BaseCore:
    templates: 
      - Framework
    sources: 
      - path: ../BaseCore
    dependencies:
      - package: Swinject
        product: Swinject
        link: true
      - package: SwinjectAutoregistration
        product: SwinjectAutoregistration
        link: true
      - package: RJSLibUF
        product: RJSLibUFNetworking  
        link: true
      - target: BaseDomain
        link: false
      - target: AppTheme
        link: false
      - target: BaseRepositories
        link: false



  BaseRepositories:
    templates: 
      - Framework
    sources: 
      - path: ../BaseRepositories
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFStorage
        link: false
      - target: BaseDomain
        link: false
      - target: Factory
        link: false
            
            
                      
  Factory:
    templates: 
      - Framework
    sources: 
      - path: ../Factory
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFStorage
        link: false
      - target: BaseDomain
        link: false
      - target: AppResources
        link: false
         
         
         
  BaseDomain:
    templates: 
      - Framework
    sources: 
      - path: ../BaseDomain
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - package: RJSLibUF
        product: RJSLibUFStorage  
        link: false
      - target: BaseConstants
        link: false
         
         
                                                  
  AppTheme:
    templates: 
      - Framework
    sources: 
      - path: ../AppTheme 
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFAppThemes
        link: true        
      - target: BaseConstants
        link: false
      - target: Extensions
        link: false
      - target: AppResources
        link: false
      - target: DevTools
        link: false          
 
 
 
  Extensions:
    templates: 
      - Framework
    sources: 
      - path: ../Extensions
    dependencies:
      - package: Pulsator
        product: Pulsator
        link: true
      - package: TinyConstraints
        product: TinyConstraints
        link: true   
      - target: DevTools
        link: false
 
 
 
  AppResources:
    templates: 
      - Framework
    sources: 
      - path: ../AppResources
    dependencies:
      - target: DevTools
        link: false
       
       
                              
  DevTools:
    templates: 
      - Framework
    sources: 
      - path: ../DevTools
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - package: Toast
        product: Toast
        link: true
      - package: RJSLibUF
        product: RJSLibUFStorage
        product: RJSLibUFBase
        link: false
      - target: PointFreeFunctions
        link: false
      - target: BaseConstants
        link: false
     
     
        
  BaseConstants:
    templates: 
      - Framework
    sources: 
      - path: ../BaseConstants
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: true
       
       
        
  PointFreeFunctions:
    templates: 
      - Framework
    sources: 
      - path: ../PointFreeFunctions
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFStorage
        link: true