

#
# DOCS
#
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

#
# SAMPLES
#
# https://gist.github.com/d-date/44510c5b4b3baf820033453bfeb235c3
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/Examples.md
#

####################### PROJECT #######################
####################### PROJECT #######################  
####################### PROJECT #######################

name: GoodToGo

options:

  bundleIdPrefix: com.GoodToGo
  xcodeVersion: '12.0.1'
  deploymentTarget: '12.0'
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: false
  minimumXcodeGenVersion: '2.18.0'

####################### AUXILIAR FOLDERS #######################
####################### AUXILIAR FOLDERS #######################  
####################### AUXILIAR FOLDERS #######################

fileGroups:
  - ../Documents

####################### CONFIGS #######################
####################### CONFIGS #######################  
####################### CONFIGS #######################

configs:

  Debug.Mock: debug
  Debug.Dev: debug
  Debug.QA: debug
  Debug.Prod: debug
  Release: release

####################### SPM #######################
####################### SPM #######################  
####################### SPM #######################

packages:

  RJSLibUF:
    url: https://github.com/ricardopsantos/RJSLibUF
    branch: master
    #minVersion: 1.0.0, maxVersion: 2.0.0

# Pulse animation for iOS
  Pulsator:
    url: https://github.com/shu223/Pulsator
    branch: master
    
# An iOS library to natively render After Effects vector animations http://airbnb.io/lottie/
#  Lottie:
#    url: https://github.com/airbnb/lottie-ios
#    branch: master

# A beautiful and flexible text field control implementation of "Float Label Pattern". Written in Swift.
  SkyFloatingLabelTextField:
    url: https://github.com/Skyscanner/SkyFloatingLabelTextField
    branch: master

# A modern, flexible logging tool
#  NSLogger:
#    url: https://github.com/fpillet/NSLogger
#    branch: master
#    from: "1.9.7"
    
# Nothing but sugar.
#  TinyConstraints:
#    url: https://github.com/roberthein/TinyConstraints
#    from: "4.0.1"
    
# A Swift extension that adds toast notifications to the UIView object class.
  Toast:
    url: https://github.com/scalessec/Toast-Swift
    branch: master
#    from: "5.0.1"
    #github "scalessec/Toast-Swift" ~> 5.0.1

####################### SETTINGS #######################
####################### SETTINGS #######################  
####################### SETTINGS #######################

settings:

  base:
    IPHONEOS_DEPLOYMENT_TARGET: 12.0
    ENABLE_BITCODE: NO
    SWIFT_VERSION: 5.2
    
  configs:
    Release: 
      ENABLE_BITCODE: YES
     
targetTemplates:

  Framework:
    type: framework
    platform: iOS
    deploymentTarget: 11.0
    settings:
      base:
        MARKETING_VERSION: 1.0
  
  UIFramework:
    type: framework
    platform: iOS
    deploymentTarget: 11.0
    settings:
      base:
        MARKETING_VERSION: 1.0
    dependencies:
      - carthage: RxRelay
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: Differentiator
      - carthage: RxDataSources
      - target: BaseDomain
        link: false
      - target: Designables
        link: false
      - target: BaseUI
        link: false
      - target: BaseConstants
        link: false
      - target: AppTheme
        link: false
      - target: Extensions
        link: false
      - target: DevTools
        link: false
            
####################### TARGETS #######################
####################### TARGETS #######################  
####################### TARGETS #######################
       
targets:
  
## Base App ## Base App ## Base App ## Base App ## Base App 

  GoodToGo:
    type: application
    platform: iOS
    deploymentTarget: 12.0
    settings:
      base:
        MARKETING_VERSION: 1.0
      configs:
        Debug.Dev: 
          CUSTOM_BUILD_SETTING: my_value_1
        Debug.QA:
          CUSTOM_BUILD_SETTING: my_value_2
        Debug.Prod:
          CUSTOM_BUILD_SETTING: my_value_3
        Debug.Mock:
          CUSTOM_BUILD_SETTING: my_value_5
        debug:
          CUSTOM_BUILD_SETTING: my_value_6
        release:
          CUSTOM_BUILD_SETTING: my_value_7
    sources:
       - path: ../GoodToGo
    dependencies:
      - carthage: RxRelay
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: Differentiator
      - carthage: RxDataSources
      - carthage: Swinject
      - carthage: SwinjectAutoregistration
      - carthage: Material
      - carthage: Motion
      - carthage: TinyConstraints
      - carthage: Lottie
      - package: RJSLibUF
        product: RJSLibUFBase
        product: RJSLibUFStorage
        product: RJSLibUFNetworking        
      - target: BaseUI
        link: false
      - target: DevTools
        link: false
      - target: UICarTrack
        link: false
      - target: UIGalleryApp
        link: false
        
    postCompileScripts:
      - script: |
                if which swiftlint >/dev/null; then
                   swiftlint
                else
                   echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        name: Run SwiftLint
   
## Specific App Related ## Specific App Related ## Specific App Related ## Specific App Related
   
  UICarTrack:
    templates: 
      - UIFramework
    sources: 
      - path: ../UICarTrack
    dependencies:
      - target: DomainCarTrack
        link: false
      - target: CoreCarTrack
        link: false
      - target: RepositoryWebAPICartrack
        link: false
              
  DomainCarTrack:
    templates: 
      - Framework
    sources: 
      - path: ../DomainCarTrack
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFNetworking  
      - target: BaseDomain
        link: false
      
  CoreCarTrack:
    templates: 
      - Framework
    sources: 
      - path: ../CoreCarTrack
    dependencies:
      - target: BaseCore
        link: false  

  RepositoryWebAPICartrack:
    templates: 
      - Framework
    sources: 
      - path: ../RepositoryWebAPICartrack  
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFNetworking  
      - target: BaseRepositoryWebAPI
        link: false  
      - target: BaseConstants
        link: false  
      - target: DevTools
        link: false
      - target: DomainCarTrack
        link: false

## Specific App Related ## Specific App Related ## Specific App Related ## Specific App Related

  UIGalleryApp:
    templates:
      - UIFramework
    sources:
      - path: ../UIGalleryApp
    dependencies:
      - carthage: Swinject
      - package: RJSLibUF
        product: RJSLibUFNetworking  
      - target: DomainGalleryApp
        link: false
      - target: CoreGalleryApp
        link: false
      - target: RepositoryWebAPIGalleryApp
        link: false
      - target: DevTools
        link: false
      - target: BaseCore
        link: false  
        
  RepositoryWebAPIGalleryApp:
    templates: 
      - Framework
    sources: 
      - path: ../RepositoryWebAPIGalleryApp  
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFNetworking  
      - target: BaseRepositoryWebAPI
        link: false  
      - target: BaseConstants
        link: false  
      - target: DevTools
        link: false   
      - target: DomainGalleryApp
        link: false   
               
  DomainGalleryApp:
    templates: 
      - Framework
    sources: 
      - path: ../DomainGalleryApp   
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFNetworking  
      - target: BaseDomain
        link: false
       
  CoreGalleryApp:
    templates: 
      - Framework
    sources: 
      - path: ../CoreGalleryApp  
    dependencies:
      - target: BaseCore
        link: false    
      
## Generic App Related ## Generic App Related ## Generic App Related ## Generic App Related
  
  Factory:
    templates: 
      - Framework
    sources: 
      - path: ../Factory
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - package: RJSLibUF
        product: RJSLibUFStorage
      - target: BaseDomain
        link: false
      - target: AppResources
        link: false
      
  BaseRepositories:
    templates: 
      - Framework
    sources: 
      - path: ../BaseRepositories
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - package: RJSLibUF
        product: RJSLibUFStorage
      - target: BaseDomain
        link: false
      - target: Factory
        link: false
      
  BaseRepositoryWebAPI:
    templates: 
      - Framework
    sources: 
      - path: ../BaseRepositoryWebAPI
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa    
      - target: DevTools
        link: false  
       
  BaseCore:
    templates: 
      - Framework
    sources: 
      - path: ../BaseCore
    dependencies:
      - carthage: Swinject
      - carthage: SwinjectAutoregistration
      - package: RJSLibUF
        product: RJSLibUFNetworking  
      - target: BaseDomain
        link: false
      - target: AppTheme
        link: false
      - target: BaseRepositories
        link: false
       
  BaseDomain:
    templates: 
      - Framework
    sources: 
      - path: ../BaseDomain
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - package: RJSLibUF
        product: RJSLibUFStorage  
      - target: BaseConstants
        link: false
         
  Designables:
    templates: 
      - Framework
    sources: 
      - path: ../Designables
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxGesture
      - carthage: TinyConstraints
      - carthage: Material
      - carthage: Motion
      - package: SkyFloatingLabelTextField
      - package: RJSLibUF
        product: RJSLibUFBase
        product: RJSLibUFALayouts 
      - target: BaseUI
        link: false
      
  Extensions:
    templates: 
      - Framework
    sources: 
      - path: ../Extensions
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: TinyConstraints
      - package: Pulsator
      - target: DevTools
        link: false
      
  AppResources:
    templates: 
      - Framework
    sources: 
      - path: ../AppResources
    dependencies:
      - target: DevTools
        link: false
      - package: RJSLibUF
        product: RJSLibUFBase
      
  BaseUI:
    templates: 
      - Framework
    sources: 
      - path: ../BaseUI
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - package: RJSLibUF
        product: RJSLibUFBase
        product: RJSLibUFAppThemes
      - target: AppResources
        link: false
      - target: AppTheme
        link: false
      - target: BaseCore
        link: false
        
  PointFreeFunctions:
    templates: 
      - Framework
    sources: 
      - path: ../PointFreeFunctions
    dependencies:
#      - carthage: RJSLibUFStorage
      - package: RJSLibUF
        product: RJSLibUFStorage
           
  AppTheme:
    templates: 
      - Framework
    sources: 
      - path: ../AppTheme 
    dependencies:
#      - carthage: RJSLibUFAppThemes
      - package: RJSLibUF
        product: RJSLibUFAppThemes
      - target: BaseConstants
        link: false
      - target: Extensions
        link: false
      - target: AppResources
        link: false
      - target: DevTools
        link: false          
       
  BaseConstants:
    templates: 
      - Framework
    sources: 
      - path: ../BaseConstants
    dependencies:
#      - carthage: RJSLibUFBase
      - package: RJSLibUF
        product: RJSLibUFBase
         
  DevTools:
    templates: 
      - Framework
    sources: 
      - path: ../DevTools
    dependencies:
      - carthage: RxCocoa
      - carthage: RxSwift
      - package: Toast
      - carthage: NSLogger
      - package: RJSLibUF
        product: RJSLibUFStorage
      - target: PointFreeFunctions
        link: false
      - target: BaseConstants
        link: false

